apiVersion: apps/v1
kind: Deployment
metadata:
  name: redeye
  labels:
    app: redeye
spec:
  replicas: 0
  selector:
    matchLabels:
      app: redeye
  template:
    metadata:
      labels:
        app: redeye
    spec:
      volumes:
        - name: redeye-files
          hostPath:
            path: /disk1/redeye/files
            type: DirectoryOrCreate
      containers:
        - name: reddeye
          image: ghcr.io/redeye-framework/redeye:latest
          command:
            - redeye.py
            - "--safe"
            - "--port"
            - "8443"
            - "--Docker"
            - "--redteam"
          env:
            - name: AUTHENTICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pass
                  key: red
            - name: NEO4J_URI
              value: bolt://neo4j.dbs.svc.cluster.local:7687
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pass
                  key: neo4j
          volumeMounts:
            - mountPath: /redeye/files
              name: redeye-files
            - mountPath: /redeye/RedDB
              name: redeye-db
          ports:
            - containerPort: 8443
