---
apiVersion: v1
kind: Service
metadata:
  name: redeye
spec:
  type: NodePort
  selector:
    app: redeye
  ports:
    - name: "http"
      protocol: TCP
      port: 8443
    - name: "neo4j"
      protocol: TCP
      port: 7687
