apiVersion: apps/v1
kind: Deployment
metadata:
    name: kali
    labels:
      app: kali
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kali
    template:
        metadata:
            labels:
                app: kali
        spec:
            dnsConfig:
              nameservers:
                - 192.168.10.142
            volumes:
                - name: tools
                  configMap:
                    name: tools

                - name: vpn-config
                  secret:
                    secretName: vpn-config
                    items:
                      - key: vpn.ovpn
                        path: vpn.ovpn

                - name: install-script
                  configMap:
                    name: kali-insall-script
                    items:
                      - key: install.sh
                        path: install.sh

                - name: tmux-conf
                  configMap:
                    name: tmux
                    items:
                      - key: .tmux.conf
                        path: .tmux.conf

                - name: ssh-conf
                  configMap:
                    name: kali-sshd
                    items:
                      - key: ssh_config
                        path: ssh_config

                - name: htb-cl
                  hostPath:
                    path: /disk1/htb
            containers:
                - name: kali
                  image: oonray/kali
                  tty: true
                  stdin: true
                  command: ["/bin/sh"]
                  volumeMounts:
                    - mountPath: /root/.htb/
                      name: htb-cl
                    - name: ssh-conf
                      mountPath: /etc/ssh/sshd_config
                      subPath: sshd_config
                  ports:
                    - containerPort: 8000
                    - containerPort: 22

                - name: openvpn
                  image: oonray/blackhat:latest
                  securityContext:
                    privileged: true
                  tty: true
                  stdin: true
                  imagePullPolicy: Always
                  volumeMounts:
                    - name: vpn-config
                      mountPath: /data/vpn/vpn.ovpn
                      subPath: vpn.ovpn
                  ports:
                    - containerPort: 1080
