apiVersion: apps/v1
kind: Deployment
metadata:
    name: kali
    labels:
      app: kali
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kali
    template:
        metadata:
            labels:
                app: kali
        spec:
            volumes:
                - name: tools
                  configMap:
                    name: tools

                - name: vpn-config
                  secret:
                    secretName: vpn-config
                    items:
                      - key: vpn.ovpn
                        path: vpn.ovpn

                - name: route-script
                  configMap:
                    name: opnevpn-script
                    items:
                      - key: route-override.sh
                        path: route-override.sh

                - name: install-script
                  configMap:
                    name: kali-insall-script
                    items: 
                      - key: install.sh
                        path: install.sh

                - name: empire-install-script
                  configMap:
                    name: empire-insall-script
                    items:
                      - key: install.sh
                        path: install.sh

                - name: busybox-script
                  configMap:
                    name: buisybox-insall-script
                    items: 
                      - key: install.sh
                        path: install.sh

                - name: tmux-conf
                  configMap:
                    name: tmux
                    items: 
                      - key: .tmux.conf
                        path: .tmux.conf
                - name: tmp
                  emptyDir: {}
            dnsConfig:
              nameservers:
                - 8.8.8.8
            initContainers:
              - name: vpn-route-init
                image: busybox
                command: ['/bin/sh', '-c', 'cp /vpn/route-override.sh /tmp/route/route-override.sh; chown root:root /tmp/route/route-override.sh; chmod o+x /tmp/route/route-override.sh;']
                volumeMounts:
                  - name: tmp
                    mountPath: /tmp/route
                  - name: route-script
                    mountPath: /vpn/route-override.sh
                    subPath: route-override.sh
            containers:
                - name: openvpn
                  image: dperson/openvpn-client
                  tty: true
                  stdin: true
                  command: ["/bin/sh","-c"]
                  args:  ["openvpn --config '/vpn/vpn.ovpn' --auth-user-pass 'vpn/auth.txt' --script-security 3 --route-up /tmp/route/route-override.sh;"]
                  securityContext:
                      privileged: true
                      capabilities:
                        add:
                          - NET_ADMIN
                  env:
                      - name: TZ
                        value: "Norway"
                  volumeMounts:
                    - name:  vpn-config
                      mountPath:  /vpn/vpn.ovpn
                      subPath: vpn.ovpn
                    - name: tmp
                      mountPath: /tmp/route
                  resources:
                    limits:
                      memory: "500Mi"
                      cpu: "0.5"

