apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: LoadBalancer
  selector:
    app: kali
  ports:
    - name: "1080"
      protocol: TCP
      port: 1082
      targetPort: 1080
    - name: "8081"
      protocol: TCP
      port: 8081
      targetPort: 8080
