apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: NodePort
  selector:
    app: kali
  ports:
    - name: "1080"
      protocol: TCP
      port: 1080
    - name: "8081"
      protocol: TCP
      port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: kali
spec:
  type: NodePort
  selector:
    app: kali
  ports:
    - name: "22"
      protocol: TCP
      port: 22
    - name: "python"
      protocol: TCP
      port: 8000
