---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thm
replicas:
  - name: kali
    count: 1
resources:
  - ad
  - ../namespace.yaml
  - ../../../base/default
  - secrets.enc.json
