apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali
spec:
  template:
    spec:
      volumes:
        - name: pass-config
          secret:
            secretName: vpn-config
            items:
              - key: pass.txt
                path: pass.txt
      containers:
        - name: openvpn
          volumeMounts:
            - mountPath: /opt/pass.txt
              name: pass-config
              subPath: pass.txt
