apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali
  labels:
    app: kali
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kali
  template:
    metadata:
      labels:
        app: kali
    spec:
      volumes:
        - name: tmux-conf
          configMap:
            name: tmux
            items:
              - key: .tmux.conf
                path: .tmux.conf
        - name: vpn-config
          secret:
            secretName: vpn-config
            items:
              - key: vpn.ovpn
                path: vpn.ovpn
        - name: htb-cl
          hostPath:
            path: /disk1/htb
      containers:
        - name: kali
          image: oonray/kali:v1.0.86
          tty: true
          stdin: true
          command: ["/bin/sh"]
          volumeMounts:
            - mountPath: /root/.htb/
              name: htb-cl
          ports:
            - containerPort: 8000
            - containerPort: 445

        - name: vpn
          image: oonray/vpn:v1.0.86
          securityContext:
            privileged: true
          imagePullPolicy: Always
          command:
            - "openvpn"
            - "/root/.vpn/vpn.ovpn"
          ports:
            - containerPort: 1080

          volumeMounts:
            - mountPath: /root/.vpn/vpn.ovpn
              name: vpn-config
              subPath: vpn.ovpn
            - mountPath: /root/.htb/
              name: htb-cl

        - name: c2
          securityContext:
            privileged: true
            runAsUser: 0
          command:
            - "/opt/sliver-server"
            - "daemon"
          image: oonray/c2:v1.0.86
          volumeMounts:
            - mountPath: /root/.htb/
              name: htb-cl
          ports:
            - containerPort: 5000
            - containerPort: 31337
            - containerPort: 8080
            - containerPort: 443
