kind: ConfigMap
metadata:
  name: resolv
apiVersion: v1
data:
  resolv.conf: |-
    search thm.svc.cluster.local svc.cluster.local cluster.local za.tryhackme.com
    nameserver 10.200.20.101
    nameserver 10.43.0.10
    options ndots:5
