apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloodhound
  labels:
    app: bloodhound
spec:
  replicas: 0
  selector:
    matchLabels:
      app: bloodhound
  template:
    metadata:
      labels:
        app: bloodhound
    spec:
      containers:
        - name: bloodhound
          image: oonray/bloodhound
          ports:
            - containerPort: 8080
