apiVersion: apps/v1
kind: Deployment
metadata:
  name: redeye
spec:
  template:
    spec:
      containers:
        - name: reddeye
          env:
            - name: NEO4J_DATABASE
              value: RedEyeWorkHTB
