---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: htb
replicas:
  - name: kali
    count: 1
  - name: kali-dns
    count: 1
resources:
  - ../../../base
  - secrets.enc.json
