---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: ad-
resources:
  - ../../../base/default
  - configmap.yaml
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
